# fly.toml app configuration file generated for anime-sub-notifier on 2026-09-18T16:18:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anime-sub-notifier"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
